AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  This template creates lambdas and apis for publication channels


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 1798
    Runtime: java21
    Architectures:
      - x86_64
    Environment:
      Variables:
        ALLOWED_ORIGIN: !Ref AllowedOrigins
        COGNITO_HOST: !Ref CognitoAuthorizationUri
        API_HOST: !Ref ApiDomain
        API_DOMAIN: !Ref ApiDomain
        CUSTOM_DOMAIN_BASE_PATH: !Ref CustomDomainBasePath
        DATAPORTEN_CHANNEL_REGISTRY_BASE_URL: !Ref DataportenChannelRegistryBaseUrl
        COGNITO_AUTHORIZER_URLS: !Join [",", !Ref CognitoAuthorizerUrls]
  Api:
    Cors:
      AllowOrigin: "'*'"
      AllowMethods: "'OPTIONS,GET'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,Access-Control-Allow-Origin'"

Parameters:
  ApiDomain:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /NVA/ApiDomain
    Description: Domain-name for the backend
  DataportenChannelRegistryBaseUrl:
    Type: String
  CustomDomainBasePath:
    Type: String
    Description: Base path mapping in CustomDomain
    Default: publication-channels-v2
  CognitoAuthorizationUri:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/NVA/CognitoUri'
  CognitoAuthorizerArn:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Reference to Cognito UserPool for the stage
    Default: CognitoAuthorizerArn
  CognitoAuthorizerUrls:
    Type: AWS::SSM::Parameter::Value<CommaDelimitedList>
    Default: CognitoAuthorizerUrls
  AllowedOrigins:
    Type: String
    Description: comma separated list of external clients that are allowed to contact the HTTP APIs, "*" indicates that all origins are allowed
    Default: '*'
  SlackSnsArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/NVA/Monitoring/SlackSnsArn'
  ChannelRegisterCacheBucketName:
    Type: 'String'
    Default: "channel-register-cache"
    Description: Name of bucket for channel register cache csv
  ApplicationConfigName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: The name of the AppConfig Application
    Default: '/NVA/AppConfig/ApplicationConfigName'
  ConfigurationProfileName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: The name of the AppConfig Configuration Profile
    Default: '/NVA/AppConfig/ApplicationConfigProfileName'
  EnvironmentName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: The name of the AppConfig Environment
    Default: '/NVA/AppConfig/ApplicationEnvironmentName'
  ApplicationIdName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: The name of the AppConfig Id
    Default: '/NVA/AppConfig/ApplicationConfigId'

Resources:

  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup

  PublicationChannelsApi:
    Type: AWS::Serverless::Api
    Properties:
      CacheClusterEnabled: true
      CacheClusterSize: "0.5"
      MethodSettings:
        - HttpMethod: 'GET'
          ResourcePath: '/~1journal~1{identifier}~1{year}'
          CacheTtlInSeconds: 3600
          CachingEnabled: true
        - HttpMethod: 'GET'
          ResourcePath: '/~1series~1{identifier}~1{year}'
          CacheTtlInSeconds: 3600
          CachingEnabled: true
        - HttpMethod: 'GET'
          ResourcePath: '/~1publisher~1{identifier}~1{year}'
          CacheTtlInSeconds: 3600
          CachingEnabled: true
        - HttpMethod: 'GET'
          ResourcePath: '/~1journal'
          CacheTtlInSeconds: 300
          CachingEnabled: false
        - HttpMethod: 'GET'
          ResourcePath: '/~1series'
          CacheTtlInSeconds: 300
          CachingEnabled: false
        - HttpMethod: 'GET'
          ResourcePath: '/~1publisher'
          CacheTtlInSeconds: 300
          CachingEnabled: false
      DefinitionBody:
        'Fn::Transform':
          Name: AWS::Include
          Parameters:
            Location: ./docs/openapi.yaml
      AccessLogSetting:
        DestinationArn: !GetAtt ApiAccessLogGroup.Arn
        Format: '{ "apiId": "$context.apiId", "requestId": "$context.requestId", "requestTime": "$context.requestTime", "requestTimeEpoch": "$context.requestTimeEpoch", "httpMethod": "$context.httpMethod", "path": "$context.path", "status": "$context.status",  "error.message": "$context.error.message" }'
      StageName: Prod
      Auth:
        DefaultAuthorizer: NONE
      EndpointConfiguration:
        Type: REGIONAL

  ChannelRegisterCacheTable:
    Type: 'AWS::DynamoDB::Table'
    UpdateReplacePolicy: Retain
    DeletionPolicy: Delete
    Properties:
      TableName: !Sub 'channel-register-cache-${AWS::StackName}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK0
          AttributeType: S
        - AttributeName: SK0
          AttributeType: S
      KeySchema:
        - AttributeName: PK0
          KeyType: HASH
        - AttributeName: SK0
          KeyType: RANGE

  ReadSecretsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:DataportenChannelRegistryClientCredentials-*'

  S3GetObjectCacheBucketPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource:
              - !Sub "arn:aws:s3:::${ChannelRegisterCacheBucketName}-${AWS::AccountId}/*"

  GetItemDynamoDbPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
            Resource:
              - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/channel-register-cache-${AWS::StackName}

  BatchWriteItemDynamoDbCacheTableManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:BatchWriteItem
            Resource:
              - !GetAtt ChannelRegisterCacheTable.Arn

  AppConfigActionsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - appconfig:GetConfiguration
              - appconfig:StartConfigurationSession
              - appconfig:GetLatestConfiguration
            Resource:
              - !Sub arn:aws:appconfig:${AWS::Region}:${AWS::AccountId}:application/${ApplicationIdName}
              - !Sub arn:aws:appconfig:${AWS::Region}:${AWS::AccountId}:application/${ApplicationIdName}/*

  LoadCacheButtonHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: no.sikt.nva.pubchannels.handler.cache.LoadCacheHandler::handleRequest
      Timeout: 900
      Policies:
        - !GetAtt BatchWriteItemDynamoDbCacheTableManagedPolicy.PolicyArn
        - !GetAtt S3GetObjectCacheBucketPolicy.PolicyArn
      ReservedConcurrentExecutions: 1
      Environment:
        Variables:
          TABLE_NAME: !Ref ChannelRegisterCacheTable
          CHANNEL_REGISTER_CACHE_BUCKET: !Ref ChannelRegisterCacheBucket
          CHANNEL_REGISTER_CACHE_S3_OBJECT: "cache.csv"

  FetchPublicationChannelByIdentifierAndYearFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: no.sikt.nva.pubchannels.handler.fetch.FetchPublicationChannelHandler::handleRequest
      Policies:
        - !GetAtt GetItemDynamoDbPolicy.PolicyArn
        - !GetAtt AppConfigActionsPolicy.PolicyArn
      Events:
        FetchPublisherByIdentifierAndYearEvent:
          Type: Api
          Properties:
            RestApiId: !Ref PublicationChannelsApi
            Path: /{type}/{identifier}/{year}
            Method: get
      Environment:
        Variables:
          TABLE_NAME: !Ref ChannelRegisterCacheTable
          APPLICATION_CONFIG_NAME: !Ref ApplicationConfigName
          APPLICATION_CONFIG_PROFILE_NAME: !Ref ConfigurationProfileName
          APPLICATION_CONFIG_ENVIRONMENT_NAME: !Ref EnvironmentName
          APPLICATION_ID: !Ref ApplicationIdName

  FetchPublicationChannelByIdentifierAndYearFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt FetchPublicationChannelByIdentifierAndYearFunction.Arn
      Action: lambda:InvokeFunction
      Principal: 'apigateway.amazonaws.com'

  SearchJournalByQueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: no.sikt.nva.pubchannels.handler.search.journal.SearchJournalByQueryHandler::handleRequest
      Events:
        SearchJournalByQueryEvent:
          Type: Api
          Properties:
            RestApiId: !Ref PublicationChannelsApi
            Path: /journal
            Method: get

  SearchJournalByQueryFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt SearchJournalByQueryFunction.Arn
      Action: lambda:InvokeFunction
      Principal: 'apigateway.amazonaws.com'

  PublicationChannelsBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !Ref CustomDomainBasePath
      DomainName: !Ref ApiDomain
      RestApiId: !Ref PublicationChannelsApi
      Stage: !Ref PublicationChannelsApi.Stage

  CreateJournalFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: no.sikt.nva.pubchannels.handler.create.journal.CreateJournalHandler::handleRequest
      Policies:
        - !GetAtt GetItemDynamoDbPolicy.PolicyArn
        - !GetAtt ReadSecretsPolicy.PolicyArn
      Events:
        CreateJournalEvent:
          Type: Api
          Properties:
            RestApiId: !Ref PublicationChannelsApi
            Path: /journal
            Method: post

  CreateJournalFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt CreateJournalFunction.Arn
      Action: lambda:InvokeFunction
      Principal: 'apigateway.amazonaws.com'

  CreateSerialPublicationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: no.sikt.nva.pubchannels.handler.create.serialpublication.CreateSerialPublicationHandler::handleRequest
      Policies:
        - !GetAtt GetItemDynamoDbPolicy.PolicyArn
        - !GetAtt ReadSecretsPolicy.PolicyArn
      Events:
        CreateJournalEvent:
          Type: Api
          Properties:
            RestApiId: !Ref PublicationChannelsApi
            Path: /serial-publication
            Method: post

  CreateSerialPublicationFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt CreateSerialPublicationFunction.Arn
      Action: lambda:InvokeFunction
      Principal: 'apigateway.amazonaws.com'

  SearchSerialPublicationByQueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: no.sikt.nva.pubchannels.handler.search.serialpublication.SearchSerialPublicationByQueryHandler::handleRequest
      Events:
        SearchJournalByQueryEvent:
          Type: Api
          Properties:
            RestApiId: !Ref PublicationChannelsApi
            Path: /serial-publication
            Method: get

  SearchSerialPublicationByQueryFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt SearchSerialPublicationByQueryFunction.Arn
      Action: lambda:InvokeFunction
      Principal: 'apigateway.amazonaws.com'

  SearchPublisherByQueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: no.sikt.nva.pubchannels.handler.search.publisher.SearchPublisherByQueryHandler::handleRequest
      Events:
        SearchPublisherByQueryEvent:
          Type: Api
          Properties:
            RestApiId: !Ref PublicationChannelsApi
            Path: /publisher
            Method: get

  SearchPublisherByQueryFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt SearchPublisherByQueryFunction.Arn
      Action: lambda:InvokeFunction
      Principal: 'apigateway.amazonaws.com'

  CreatePublisherFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: no.sikt.nva.pubchannels.handler.create.publisher.CreatePublisherHandler::handleRequest
      Policies:
        - !GetAtt GetItemDynamoDbPolicy.PolicyArn
        - !GetAtt ReadSecretsPolicy.PolicyArn
      Events:
        CreatePublisherEvent:
          Type: Api
          Properties:
            RestApiId: !Ref PublicationChannelsApi
            Path: /publisher
            Method: post

  CreatePublisherFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt CreatePublisherFunction.Arn
      Action: lambda:InvokeFunction
      Principal: 'apigateway.amazonaws.com'

  SearchSeriesByQueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: no.sikt.nva.pubchannels.handler.search.series.SearchSeriesByQueryHandler::handleRequest
      Events:
        SearchSeriesByQueryEvent:
          Type: Api
          Properties:
            RestApiId: !Ref PublicationChannelsApi
            Path: /series
            Method: get

  SearchSeriesByQueryFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt SearchSeriesByQueryFunction.Arn
      Action: lambda:InvokeFunction
      Principal: 'apigateway.amazonaws.com'

  CreateSeriesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: no.sikt.nva.pubchannels.handler.create.series.CreateSeriesHandler::handleRequest
      Policies:
        - !GetAtt GetItemDynamoDbPolicy.PolicyArn
        - !GetAtt ReadSecretsPolicy.PolicyArn
      Events:
        CreateSeriesEvent:
          Type: Api
          Properties:
            RestApiId: !Ref PublicationChannelsApi
            Path: /series
            Method: post

  CreateSeriesFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt CreateSeriesFunction.Arn
      Action: lambda:InvokeFunction
      Principal: 'apigateway.amazonaws.com'

  UpdatePublicationChannelFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: no.sikt.nva.pubchannels.handler.update.UpdatePublicationChannelHandler::handleRequest
      Policies:
        - !GetAtt ReadSecretsPolicy.PolicyArn
      Events:
        UpdateChannelEvent:
          Type: Api
          Properties:
            RestApiId: !Ref PublicationChannelsApi
            Path: /{type}/{identifier}
            Method: put

  UpdatePublicationChannelFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt UpdatePublicationChannelFunction.Arn
      Action: lambda:InvokeFunction
      Principal: 'apigateway.amazonaws.com'

  DataportenChannelRegistryHealthCheck:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        Port: 443
        Type: HTTPS
        ResourcePath: /health
        FullyQualifiedDomainName: !Select [ 2, !Split [ "/", !Ref DataportenChannelRegistryBaseUrl ] ] # Extracts the domain name from the URL
        RequestInterval: 30
        FailureThreshold: 2
        EnableSNI: true

  DataportenChannelRegistryHealthAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub External-Dataporten-Channel-Registry-API-HealthCheck-${PublicationChannelsApi} # PublicationChannelsApi is here just to make the name unique
      AlarmDescription: Check if external Dataporten Channel Registry API is healthy
      Namespace: AWS/Route53
      MetricName: HealthCheckStatus
      Dimensions:
        - Name: HealthCheckId
          Value: !GetAtt DataportenChannelRegistryHealthCheck.HealthCheckId
      Statistic: Minimum
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: LessThanThreshold
      AlarmActions:
        - !Ref SlackSnsArn
      TreatMissingData: notBreaching

  ChannelRegisterCacheBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ChannelRegisterCacheBucketName}-${AWS::AccountId}"

